@token = BQB0qUP1zCyEpzYe2kgC60FSWl3dzXRb2VMZB7rSUdoFO07bdvGxAodEfQ4uhLRdea-k5SdMn-Ugh97cySUS9VwwJItJL_lOEa5DmUBi4c7YhwGWQJoxztWm5MgraYrQoAs9DQnxcQHcdVD3_sGDI32iauS57T9DRlpVLfNHe8VlqzggiYQu3IBGvYcu1cutJoK5V7Sa3117VUv8vFVXE8h3ZkrV-ZlOyCqMhGK9PkRcsp0oBNql6iA2JqJAyJdG110xuCudO39ClwK_iuPtZgGpd_ellZC-x6qDxVrxtTh-4Y_EUTCrCN-iNf1iHkVSOlFJLmEMjQJXfStdRZQ
POST http://localhost:8000/admin/reset

### Ping the backend to check it's up and responding
GET http://localhost:8000/admin/ping

### Import user profile
POST http://localhost:8000/user/profile
Content-Type: application/json

{
  "access_token": "{{token}}"
}

### Import user top 20 tracks
POST http://localhost:8000/user/top-tracks
Content-Type: application/json

{
  "access_token": "{{token}}"
}

### Import user's liked tracks
POST http://localhost:8000/user/liked-tracks
Content-Type: application/json

{
  "access_token": "{{token}}"
}

### Import user's recently played tracks
POST http://localhost:8000/user/recently-played
Content-Type: application/json

{
  "access_token": "{{token}}"
}

### Import all user playlists
POST http://localhost:8000/playlists/import
Content-Type: application/json

{
  "access_token": "{{token}}"
}

### Import all tracks from the user's playlists
POST http://localhost:8000/playlists/tracks
Content-Type: application/json

{
  "access_token": "{{token}}"
}

### Refresh playlist tracks only if the snapshot_id has changed
POST http://localhost:8000/playlists/snapshots
Content-Type: application/json

{
  "access_token": "{{token}}"
}

### Get content-based recommendations for a user
GET http://localhost:8000/recommendations?access_token={{token}}

### Seed global new track releases into DB (up to 200 albums)
POST http://localhost:8000/seeds/new-releases
Content-Type: application/json

{
  "access_token": "{{token}}",
  "max_albums": 50
}

### Get top genres for a user
GET http://localhost:8000/stats/top-genres?access_token={{token}}

### Get top artists for a user
GET http://localhost:8000/stats/top-artists?access_token={{token}}

### Get track summary for a user
GET http://localhost:8000/stats/track-summary?access_token={{token}}


### Creates a custom playlist using a list of track IDs
POST http://localhost:8000/playlists/build
Content-Type: application/json

{
  "access_token": "{{token}}",
  "track_ids": ["0tduSYti0mY7p8j5AIO4Pg", "7LhBiqLbHd4BichEUoo6rJ"],
  "playlist_name": "My AI Generated Mix 2"
}

### Combine two playlists into a new one
POST http://localhost:8000/playlists/combine
Content-Type: application/json

{
  "access_token": "{{token}}",
  "playlist_ids": ["3U9cVsRVEC3gG8TIaQpl7n", "4o6bpaBOrsk2ir0A3CQL2x"],
  "playlist_name": "My Combined Playlist"
}


### Delete removed playlists
POST http://localhost:8000/playlists/prune
Content-Type: application/json

{
  "access_token": "{{token}}"
}


### Enrich track metadata for a specific user
POST http://localhost:8000/tracks/enrich
Content-Type: application/json

{
  "access_token": "{{token}}",
  "mode": "user"
}

### Enrich all missing track metadata globally
POST http://localhost:8000/tracks/enrich
Content-Type: application/json

{
  "access_token": "{{token}}",
  "mode": "global"
}




